# Generated by Django 4.1.2 on 2022-10-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="word",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
