# Generated by Django 4.1.2 on 2022-10-15 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dictionary", "0003_definition"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="definition",
            name="word",
        ),
        migrations.AddField(
            model_name="definition",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="word",
            name="definition",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="dictionary.definition",
            ),
            preserve_default=False,
        ),
    ]
