# Generated by Django 4.1.2 on 2022-10-18 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0004_remove_definition_word_definition_author_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="word",
            name="definition",
        ),
        migrations.AddField(
            model_name="definition",
            name="word",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="dictionary.word",
            ),
            preserve_default=False,
        ),
    ]
