# Generated by Django 4.1.2 on 2022-10-21 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "dictionary",
            "0006_author_category_comment_contact_emailsignup_jargon_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="auth_status",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="author",
            name="author",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="author",
            name="author_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="author/",
                verbose_name="Author Profile Image",
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="designation",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="author",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="author",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="First Name"
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Last Name"
            ),
        ),
    ]
